<?php

/**
* Implements hook_ctools_plugin_api().
*/
function tasty_backend_media_ctools_plugin_api($owner, $api) {
  if ($owner == "page_manager" && $api == "pages_default") {
    return array("version" => "1");
  }
}

/**
 * Implements hook_views_api().
 */
function tasty_backend_media_views_api() {
  return array("version" => "3.0");
}

/**
 * Implements hook_menu_local_tasks_alter().
 */
function tasty_backend_media_menu_local_tasks_alter(&$data, $router_item, $root_path) {
  // Add action link to 'file/add' on 'admin/manage/files/list' page. Modeled after media module function.
  if ($root_path == 'admin/manage/files/list') {
    $item = array(
      'title' => t('Add file'),
      'href' => 'file/add',
      'localized_options' => array(
        'query' => array('destination' => 'admin/manage/files/list'),
        'attributes' => array(
          'title' => t('Add new file'),
        ),
      ),
    );
    
    $data['actions']['output'][] = array(
      '#theme' => 'menu_local_action',
      '#link' => $item,
    );
  }
}

/**
 * Override or insert variables into the page templates.
 */

function tasty_backend_media_preprocess_page(&$variables, $hook) {
  // Can't user menu_get_object() since views messes with it - https://api.drupal.org/comment/45018#comment-45018.
  $router_item = menu_get_item();
  $path = $router_item['path'];
  // Add redirect to file/add with destination query.
  if ($path == 'file/add') {
    if (!isset($_GET['destination'])) {
      drupal_goto('file/add', array('query' => array('destination' => 'admin/manage/files/list')));
    }
  }
}

/**
 * Implements hook_menu_link_alter().
 *
 * Set file add link to be child of our files link.
 */
function drumeleon_menu_link_alter(&$item) {
  if ($item['link_path'] == 'file/add') {
    // Get the mlid of the files navigation menu link.
    $result = db_select('menu_links', 'ml')
      ->fields('ml')
      ->condition('router_path', 'admin/manage/files','=')
      ->execute()
      ->fetchAssoc();
    $mlid = $result['mlid'];
    
    // Alter the link data.
    $item['plid'] = $mlid;
    $item['weight'] = 1;
  }
}